name: Deploy react-concepts to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # use-layout-effect
      - name: build - 01-use-layout-effect
        working-directory: 01-use-layout-effect
        run: |
          npm i
          npm run build

      # use-reducer
      - name: build - 02-use-reducer
        working-directory: 02-use-reducer
        run: |
          npm i
          npm run build

      # use-imperative-handle
      - name: build - 03-use-imperative-handle
        working-directory: 03-use-imperative-handle
        run: |
          npm i
          npm run build

      # presentational-container-component
      - name: build - presentational-container-component
        working-directory: presentational-container-component
        run: |
          npm i
          npm run build

      # tanstack
      - name: build - tanstack
        working-directory: tanstack
        run: |
          npm i
          npm run build

      # swr
      - name: build - swr
        working-directory: swr
        run: |
          npm i
          npm run build

      # react-window
      - name: build - react-window
        working-directory: react-window
        run: |
          npm i
          npm run build

      # react-virtualized
      - name: build - react-virtualized
        working-directory: react-virtualized
        run: |
          npm i
          npm run build

      # emotion
      - name: build emotion
        working-directory: emotion
        run: |
          npm i
          npm run build

      # sass-less
      - name: build sass-less
        working-directory: sass-less
        run: |
          npm i
          npm run build


      - name: Prepare sites
        run: |
          mkdir site
          mv 01-use-layout-effect/dist site/01-use-layout-effect
          mv 02-use-reducer/dist site/02-use-reducer
          mv 03-use-imperative-handle/dist site/03-use-imperative-handle
          mv presentational-container-component/dist site/presentational-container-component
          mv tanstack/dist site/tanstack
          mv swr/dist site/swr
          mv react-window/dist site/react-window
          mv react-virtualized/dist site/react-virtualized
          mv emotion/dist site/emotion
          mv sass-less/dist site/sass-less

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
